input: Implement Golang Input plugin interface and added input example
fluent/fluent-bit-go pull request #52
Opened 2022-03-11 08:53 UTC by cosmo0920

This PR can work with https://github.com/fluent/fluent-bit/pull/5056.

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

2022-03-14 12:35 UTC, l2dy requested changes

2022-03-14 12:35 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
`packed` and associated data may be freed or reused by Go runtime after control flow ends in `FLBPluginInputCallback()`. Passing the `data` pointer to C will cause undefined behavior.

Please adhere to valid [`unsafe.Pointer`](https://pkg.go.dev/unsafe#Pointer) patterns.

2022-03-15 03:26 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
Thanks for the info.
Should I wrap msgpack payload with `*reflect.SliceHeader` and cast `*C.void` type.
But I'm not sure this commit is correct: https://github.com/fluent/fluent-bit-go/pull/52/commits/c23143fb0fd514fce3533421bf2432e349bdb8e8

2022-03-15 14:21 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
> Moreover, the Data field is not sufficient to guarantee the data it references will not be garbage collected, so programs must keep a separate, correctly typed pointer to the underlying data.

[`reflect.SliceHeader`](https://pkg.go.dev/reflect#SliceHeader) does not help, because the data referenced may still be garbage collected.

Consider it this way: When should the memory allocated for `data` be freed? It must not be freed before Fluent Bit reads its content, but the Go runtime does not know when would that happen. Unless every piece of data is persisted in memory (i.e. memory leak), we need a second callback to free it in Go memory.

P.S. https://pkg.go.dev/cmd/cgo#hdr-Passing_pointers is worth reading.

2022-03-15 14:46 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
> [...] the term Go pointer means a pointer to memory allocated by Go (such as by using the & operator or calling the predefined new function)
>
> *A Go function called by C code may not return a Go pointer* (which implies that it may not return a string, slice, channel, and so forth).

We have to copy data to memory allocated by C, either with `C.CBytes` in Go code or by calling C code in Go.

2022-03-16 08:33 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
Hmm..., got it. I'm considering what is the better way to handle this memory handling issue.

2022-03-16 08:53 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
In my understanding, cgo function's arguments passed pointers are not GC-ed and C.malloc allocated memories are also GC-ed. Using runtime finalizers can be used for GC-like C allocated memory.
I added that implementation in https://github.com/fluent/fluent-bit-go/pull/52/commits/09b21347ec2aad577e619688833611012cf2e822.

2022-03-16 14:44 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
> In my understanding, cgo function's arguments passed pointers are not GC-ed and C.malloc allocated memories are also GC-ed.

Both are not GC-ed. It is the caller's responsibility to arrange for them to be freed.

> Using runtime finalizers can be used for GC-like C allocated memory. I added that implementation in [a810b68](https://github.com/fluent/fluent-bit-go/commit/a810b68c90fb170f354e2e272b5bff48d621703b).

I don't think it will work without a second callback, either into C or Go. When do you expect Go runtime to call this finalizer? Would it be synchronized with Fluent Bit code reading `data`?

2022-03-17 04:36 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
I got it.
I added the second callback to deallocate heap memories:
fluent-bit-go: https://github.com/fluent/fluent-bit-go/pull/52/commits/46f69ba45c777b0e4bb69ec2cac383d5a229a053
Fluent Bit: https://github.com/cosmo0920/fluent-bit/commit/c3302a70f54e5819050e193b00d9069452fa0e61

2022-03-17 08:35 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
I decided that freeing allocated heap memories by C style heap allocations is in: https://github.com/fluent/fluent-bit/pull/5056/files#diff-1450925bb990981ecd92583bfe8365287efa31c03bfab35a2332161b27fff6b5R96-R98
This is still valid code and no causing memory leaks.

2022-03-17 12:25 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
> I decided that freeing allocated heap memories by C style heap allocations is in: https://github.com/fluent/fluent-bit/pull/5056/files#diff-1450925bb990981ecd92583bfe8365287efa31c03bfab35a2332161b27fff6b5R96-R98 This is still valid code and no causing memory leaks.

In theory it should work, but I'm not sure if it works with jemalloc (Fluent Bit built with `-DFLB_JEMALLOC=On`).

2022-03-17 15:01 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
Sure, I'll test for that configure option.

2022-03-17 15:44 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	return C.calloc(C.size_t(size), 1)
What happens if `calloc()` failed?

2022-03-18 02:57 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(&packed[0])
There's no SEGV occurred. Fluent Bit with bundled jemalloc can work with this Golang shared object.

2022-03-18 03:42 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	return C.calloc(C.size_t(size), 1)
Hmm.., I'm not sure.
For C.malloc, Golang builtin system can handle like as:
https://github.com/golang/go/blob/635e49388bf746a2b8c7ab1e9026aede0eb88b31/src/cmd/cgo/out.go#L1696

And official documentation says that:

> As a special case, C.malloc does not call the C library malloc directly but instead calls a Go helper function that wraps the C library malloc but guarantees never to return nil. If C's malloc indicates out of memory, the helper function crashes the program, like when Go itself runs out of memory. Because C.malloc cannot fail, it has no two-result form that returns errno. 

https://pkg.go.dev/cmd/cgo#hdr-Go_references_to_C

2022-03-18 03:50 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	return C.calloc(C.size_t(size), 1)
I added a nil check for `C.calloc` returned pointer at: https://github.com/fluent/fluent-bit-go/pull/52/commits/902b44ad25dc369a65189e38626d2a9d6c6282da

2022-03-20 12:08 UTC, l2dy approved these changes
LGTM, but more comments would be appreciated, especially on use of reflection and memory allocation.

2022-03-20 12:08 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	copy(s.Data, packed)
Have you tried `C.CBytes()`?

2022-03-22 04:09 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	copy(s.Data, packed)
No, I didn't. But calling `C.CBytes` is not appropriate because `C.CBytes` calls `malloc` internally but we need only copying values from `packed variable which includes encoded msgpack payload to `s.Data`.

2022-03-22 13:28 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	copy(s.Data, packed)
If `C.CBytes` is used, we don't need `s.Data` at all. The `unsafe.Pointer` returned can be assigned to `data` directly.

2022-03-22 13:32 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	copy(s.Data, packed)
Note that `C.CBytes([]byte)` itself copies data in the slice argument to the allocated memory, so there is no need to call `copy()` yourself.

2022-03-23 07:47 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	copy(s.Data, packed)
Hmm..., I see. I confirmed that `C.CBytes` is also working for this purpose.

2022-03-23 08:31 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	copy(s.Data, packed)
Fixed in https://github.com/fluent/fluent-bit-go/pull/52/commits/ce232298cf491521ee2f2dab8d787a41442f8f7c.

2022-03-23 13:46 UTC, l2dy commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(C.CBytes(packed))
`C.CBytes()` returns `unsafe.Pointer`, so there is no need for explicit conversion.

2022-03-24 01:17 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(C.CBytes(packed))
Oh, I'd overlooked it. Thanks for your advice. :smile:

2022-03-24 01:40 UTC, cosmo0920 commented on examples/in_gdummy/in_gdummy.go
> +	*data = unsafe.Pointer(C.CBytes(packed))
Fixed in https://github.com/fluent/fluent-bit-go/pull/52/commits/b19ba6c9e5f21cfdd8b6ea4c1cace9892389f6ac

2022-04-06 17:37 UTC, nicolasparada commented on examples/in_gdummy/README.md
> +	return input.FLBPluginRegister(def, "gdummy", "dummy Go!")
This could be part of the config file instead.
````
[PLUGINS]
  Name        gdummy
  Description dummy Go!
  Path        dummy.so

2022-04-06 18:27 UTC, nicolasparada requested changes
I found this design too C-ish.
Usage of CGO, unsafe pointers and `int` instead of errors. Doesn't look like golang code at all.

It also expose some internal details of fluent bit that make very difficult for plugins authors to get starting.

I propse introducing a golang bridge.
We could have a piece of golang code that uses CGO and communicates with fluentbit, and this bridge is gonna use the [`plugin`](https://pkg.go.dev/plugin) package to load the real plugin writen with idiomatic golang code.

So the bridge would be a golang file built with `c-shared` mode.
And the plugin will be a golang file built with `plugin` mode.

We can have a third party golang package that is pure, free of any CGO that exposes certain interfaces to work with fluentbit.
Like:

```go
// ConfLoader load values by the key defined in the plugin config.
// Example:
// [PLUGINS]
//   Name: myplugin
//   Path: myplugin.so
//   foo: bar
//
// Then `conf.Load("foo") == "bar"`
type ConfLoader interface {
  Load(key string) string
}
```

This way we can pass this conf loader interface to the plugin and the author of the plugin doesn't have to treat with a shared piece of memory.

Or this:

```go
// Logger logs the given data at the given time to fluentbit as if it were an input source.
type Logger interface {
  Log(t time.Time, data map[string]string) error
}
```
Internally this will be a write to the msgpack encoder, but this way, the plugin author doesn't have to deal with unknown message formats, pointers, or have to know if the write is gonna be queued or sync-writen, or about flush intervals, or anything.

The plugin itself could be simplified.
Plugin authors should not have to worry about the phases. They should be able to structure the plugin the way they want.
We just need to offer the necessary interfaces.

I propose that the plugin could receive the interfaces from before in a single exported method.

```go
package main

import plugin "github.com/calyptia/go-fluentbit-plugin"

var Plugin = plugin{}

type plugin struct {}

func (p *plugin) Process(ctx context.Context, conf plugin.ConfLoader, logger plugin.Logger) error {
  foo := conf.Load("foo")
  return logger.Log(time.Now(), map[string]string{
    "foo": foo,
  })
}
```

We should check that the plugin has a `Plugin` symbol (this symbol name could be even configured at the config file) and that it implements the processor interface:

```go
type Processor interface {
  Process(ctx context.Context, conf ConfLoader, logger Logger) error
}
```

The bridge would load the plugin and communicate to fluentbit through shared memory. Let just not make plugin authors have to deal with shared memory.

2022-04-07 02:45 UTC, cosmo0920 commented on examples/in_gdummy/README.md
> +	return input.FLBPluginRegister(def, "gdummy", "dummy Go!")
Config File should handle several configs for output and input (for the future).
If we would support this format, Golang output plugin config format will break.
I don't want to introduce this breakage on this golang package.

2022-04-07 02:45 UTC, cosmo0920 commented on examples/in_gdummy/README.md
> +	return input.FLBPluginRegister(def, "gdummy", "dummy Go!")
ditto.

2022-04-07 02:54 UTC, cosmo0920 commented on examples/in_gdummy/README.md
> +	return input.FLBPluginRegister(def, "gdummy", "dummy Go!")
Instead, loading description from ordinary `[INPUT]` field is a slightly reasonable but other Fluent Bit statically linked input plugins do not have such feature. I think that we should unify behavior for description and name.

`Name` will be handled in `[INPUT]` section.
This `[PLUGIN]` section is used only for registering to search paths.

2022-04-07 07:59 UTC, cosmo0920 commented
Using Golang plugin mechanism is quite reasonable. But, in this golang module ("github.com/fluent/fluent-bit-go/input"), we should keep as very thin package.
Providing another wrapper module is reasonable for me.

2022-04-08 02:53 UTC, nicolasparada commented
I think that package should be part of the bridge code. Since it uses CGO and shares memory with fluentbit.

2022-04-08 02:54 UTC, nicolasparada commented
Plugin authors should not have to import any code that includes CGO.
As soon as you use CGO, you loose most of the golang goodies.

2022-04-08 03:24 UTC, cosmo0920 commented
I mean, plugin authors can choose to import plugin bridge code something like `"github.com/fluent/fluent-bit-go/bridge/input"` but this PR shouldn't include patches for bridging code. We should do it in another PR.
Already, output Golang plugin uses CGO included code.
We should unify the behavior and coding style for output and input modules.
Additionally, we should provide bridging code for simplicity to write Golang input plugin.

2022-07-11 02:21 UTC, zhu733756 commented
Good job! Can you also add some examples to use this plugin? Thanks.

2022-08-05 22:47 UTC, nokute78 commented
Note: A patch https://github.com/fluent/fluent-bit/pull/5056 to support golang input plugin was merged.

2022-08-08 00:03 UTC, cosmo0920 commented
Yeah, we noticed that but current fluent-bit is pointed for 2.0 development. If we will merge this PR, we have to create 2.0 branch for now.

2022-11-28 13:24 UTC, jan-zajic commented
Hi guys, 2.0 version has been out for a while now, so please merge this PR, thank you.

2022-11-28 14:13 UTC, merged

2022-11-28 14:14 UTC, edsiper commented
thanks!